version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    networks:
      - webproxy
    environment:
      - CADDY_ADMIN=0.0.0.0:2019

  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: deltastudio-server
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN:-}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - DOCKER_HOST=/var/run/docker.sock
    networks:
      - webproxy
      - monitoring

networks:
  webproxy:
    external: true
  monitoring:
    external: true

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:
  netdata_config:
  netdata_lib:
  netdata_cache: